#!/bin/zsh
# Activate the LeRobot environment
source "$(dirname "$0")/lerobot/.venv/Scripts/activate"
export PATH="$(dirname "$0")/tools:$PATH"
echo "LeRobot environment activated."
echo "Python: $(python --version)"
echo ""
echo "Available commands:"
echo "  lerobot-find-port        - Find USB port for the arm"
echo "  lerobot-setup-motors     - Configure motor IDs (first-time setup)"
echo "  lerobot-calibrate        - Calibrate the arm"
echo "  lerobot-teleoperate      - Teleoperate follower with leader arm"
echo "  lerobot-record           - Record a dataset"
echo "  lerobot-train            - Train a policy"
echo ""
echo "Quick start:"
echo "  1. Plug in arm, then: lerobot-find-port"
echo "  2. First time only:   lerobot-setup-motors --robot.type=so101_follower --robot.port=<port>"
echo "  3. Calibrate:         lerobot-calibrate --robot.type=so101_follower --robot.port=<port> --robot.id=my_arm"
echo "  4. Teleoperate:       see test_so101.py for API usage"
